### ISSUE TITLE
이니셜 디자인

### ISSUE THREAD

**Issue by kkweon** [dl4ab/conversion#1]
첫 목표로 아래와 같이 사용할 수 있는 라이브러리를 만드는 것을 목표로.

```go
import (
  "fmt"
  "github.com/dl4ab/conversion"
)

func main() {
  var floatValue float32 := 3.123
  b, err := conversion.Float32ToByteSlice(floatValue)
  r, err := conversion.ByteSliceToFloat32(b)
  
  fmt.Println(r) // 3.123
}
```

컨벤션은 다음과 같이 함이 어떨가 싶습니다.

```go
func TypeAToTypeB(x TypeA) (TypeB, error) {

}

**Comment by kkweon** [comment]
```go
func Float32SliceToByteSlice(floatSlice []float32) ([]byte, error) {
}

func ByteSliceToFloat32Slice(byteSlice []byte) ([]float32, error) {
}
```

**Comment by nicewook** [comment]
1. 위에는 float32 이고 아래에는 []float32 인데 저는 []float32 를 변환하는걸 어렵게 느껴서 질문이 시작되었습니다.
2. Endian 문제에 대한 고려는 어떻게 해야 할까 싶기도 합니다.

**Comment by nicewook** [comment]
Float32SliceToByteSlice -> Float32sToBytes 또는 F32sToBytes 정도면 어떨까요?

**Comment by kkweon** [comment]
`float32 -> []byte` 로 바꿀 수 있고
1 `float32` 은 4 `byte` 이기 때문에

`[]float32 -> [][4]byte -> []byte` (flatten 통해서) 만들 수 있습니다.

흠 저는 원 타입 이름 그대로 쓰는게 좋을 것 같습니다.

함수 이름만 봐도 무엇을 하는지 predictable 해야 되는데
아무 생각 없이 **Float32sToBytes** 본다면 이게 무엇인지 가늠이 되지 않는 것 같슴니당

**Comment by kkweon** [comment]
음 생각해보니 괜찬은것 같기도 한데요

Float을 줄이는건 좀 헷갈릴것 같구요. **s** 복수만 붙여주는 거라면 사용자 입장에서 꽤 깔끔한것 같습니다.

**Comment by kkweon** [comment]
```go
type Endian int
const BigEndian Endian = 0
const LittleEndian Endian = 1

type Option struct {
  EndianOption Endian
}

const defaultOption = Option { BigEndian }

func Float32sToBytes(xs []float32, option *Option) ([]byte, error) {

}
```

`option` 이 `nil` 이면 BigEndian 기본으로 하는식으로요
이런식이 되야 될 것 같네요.

**Comment by nicewook** [comment]
멋집니다. @@

1. Option 은 향후 확장성을 고려하신 설계로 보면 되겠지요? 파라미터 전달을 reference 로 하는건 특별한 의미가 있나요? 라고 질문하고 보니 nil 을 사용하는 의미가 있군요. @@
2. 생성된 []byte 가 어떤 Endian 으로 되었는지를 리턴값으로 알 수 있으면 더 좋겠다 싶지만 그정도까지는 그냥 문맥적, 혹은 약속으로 알아둬야 겠지요? 
3. xs 는 무슨 의미일까요?

**Comment by kkweon** [comment]
1.  pointer 로 전달하는건 유저 입장에서 일부러 option을 꺼내지 않고 사용할 수 있어 사용이 쉽고 굳이 struct를 copy 하지 않기 위함입니다. 비록 지금은 enum 한개만 있어 값이 작아보이지만요. little endian을 사용하는 곳이라면 little endian option struct를 하나 생성해놓고 계속 돌려 쓸 수 있죠.
2. 흐음 이건 꽤 low level 에 해당하기 때문에 유저 입장에서 얼마든지 wrapper를 만들 수 있을 것 같습니다. 이미 확장이 가능하기 때문에 이걸 이 라이브러리 레벨에서 구현하려고 가지고 내려오려면 꼭 필요한가에 대한 대답이 되어야 되는데 제가 볼때는 꼭 필요하다고 생각하지 않는데요. 꼭 필요하다고 생각하시면 아마 다른 구조가 필요할 것 같은데 알려주세요. 제가 생각하는 방식으로는 사용자 입장에서 조금 귀찮아질 것 같습니다. 
3.  x가 여러개어서 x**s** 입니다. 이건 알고리즘 네이밍 습관임니다.

**Comment by nicewook** [comment]
말씀하신 내용에 모두 공감합니다. @@

**Comment by kkweon** [comment]
그럼 천천히 심심할때마다 시작하도록 하시지요.

Issues 들 적어놓았으니 심심하실때마다 원하는 거 선택해서 assign self 하시고 작업하시면 됨니다요

**Comment by nicewook** [comment]
이렇게 일하는 방법을 배워가는게 재미있네요.
