### ISSUE TITLE
testing private functions 

### ISSUE THREAD

**Issue by TangoEnSkai** [dl4ab/conversion#10]
## Background

Currently, we are testing private functions by calling directly calling from testing functions, for example, let's say we have `hoge.go` like below: 

```go
package hoge

func Public() {
  ...
  private()
  ...
}

...
func private() {
   ...
}
```

and it's test, `hoge_test.go` has test functions like:

```go
package hoge

func TestPublic(..) {..}
func TestPrivate(..){..}

```

The thing is:

- in the real world, it's not possible to call the private function directly 
  - `hoge.private()` is not legal
- we expect the `private()` function is always executed by calling `Public()` function

## Suggestion 

- add a test cases and run `TestPublic` to trigger `private()` function 
- separate `hoge_test.go` from `package hoge`, and define a new package called `package hoge_test`
  - and import the package `hoge` to avoid calling private functions
    - e.g. with `import hoge` under `package hoge_test` you are not able to call `hoge.private()` directly.

**Comment by kkweon** [comment]
conversion 같은 경우

유틸함수들을  internal package 로 옮겨서 internal public 으로 해서 테스트코드 작성하는게 좋을 것 같습니다.

확실히 퍼블릭에 노출 될건 아니고 그 인터널 온니 함수들에 대한 테스트는 필요해보입니다.

**Comment by TangoEnSkai** [comment]
@kkweon 답변 감사합니다. 

> 인터널 온니 함수들에 대한 테스트는 필요해보입니다.

동의합니다. 

아 예제가 별로 좋은 케이스는 아닌 것 같긴한데요, 일반적인 피쳐 구현이나 이런 경우에 private 함수 테스트를 바로 바로 하는것에 대해서 좀 궁금했습니다. 

슬랙 [댓글](https://deeplearning4allbaksu.slack.com/archives/C9M36H2QL/p1593800733104100?thread_ts=1593800442.103900&cid=C9M36H2QL)도 감사합니다!
