### ISSUE TITLE
Define a constant instead of duplicating this literal "%#02v\n" 3 times.

### ISSUE THREAD

**Issue by kkweon** [dl4ab/conversion#14]
https://sonarcloud.io/project/issues?id=dl4ab_conversion&open=AXMcmR0vgfCQA9kHQZkb&resolved=false&types=CODE_SMELL

**Comment by TangoEnSkai** [comment]
이슈도 함꼐 닫아도 될까요?　

ref: https://github.com/dl4ab/conversion/pull/16#discussion_r488295724

**Comment by kkweon** [comment]
감사합니다
