### ISSUE TITLE
Uint64 <-> []byte가 꽤나 의미가 있을 것 같습니다.

### ISSUE THREAD

**Issue by nicewook** [dl4ab/conversion#23]
Java, MongoDB등에서 uint64를 지원하지 않는 것으로 아는데 이 경우에 []byte로 변환해서 소통을 하면 좋겠네요. 

- 이런 이야기를 이슈에서 나눠도 될지 모르겠습니다.

**Comment by kkweon** [comment]
out of scope 같네요. 다른 언어간 커뮤니케이션은 protocol buffer 등을 이용해주시면 될듯. 

예를 들어 java 에서는 Long 타입을 사용하고 (unsigned method 가 붙어있음)
mongodb 에서는 int64 로 저장하던가 ObjectID 를 사용하겠죠.

**Comment by nicewook** [comment]
패키지를 확장해서 무얼 하자는 이야기는 아니었고 패키지의 이 기능을 이용할 수 있겠다는 생각을 적어본 것이었습니다. :-)
아무튼 말씀하신 내용도 현재 업무에서 참고가 되겠네요. 감사합니다.

**Comment by nicewook** [comment]
이슈는 닫겠습니다
