### ISSUE TITLE
Define Float32sToBytes & BytesToFloat32s and do the same for float64

### ISSUE THREAD

**Issue by kkweon** [dl4ab/conversion#4]
Note that it should return `[]byte` instead of `[][]byte`.

Internally, it should use `flattenBytes` and `unflattenBytes` since most standard APIs use `[]byte`

**Comment by ssaru** [comment]
이슈에 불쑥 껴들어서 죄송합니다. 매우 재밌어보입니다 ㅎㅎ
이슈만 보더라도 이렇게 배울 수 있군요!
